### ISSUE TITLE
Lich error breaking ;combat-trainer during hunting

### ISSUE THREAD

**Issue by Maledar** [rpherbig/dr-scripts#1870]
pastebin of problem it occurs at the end

--- Lich: error: undefined method `necro_casting?' for #<Scripting::LootProcess:0xceb3ed8>
    combat-trainer:538:in `arrange_mob'
    combat-trainer:519:in `dispose_body'
--- Lich: combat-trainer has exited.

https://pastebin.com/q6SGFw5e

**Comment by Maledar** [comment]
It's been fixed

**Comment by jandersson** [comment]
Sorry about the trouble, bad pull request from me
